# Generated by Django 2.2.4 on 2019-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0002_auto_20190815_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='parcel_owner_name',
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_address_string',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_day_of_week',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_event_closed',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_event_opened',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_response_zone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_sub_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_units_involved',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_weather_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_land_sq_ft',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_land_value',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_mail_address',
            field=models.TextField(default=''),
        ),
    ]
