# Generated by Django 2.2.4 on 2019-08-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0004_parcel_parcel_polygon_string_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='parcel_owner_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
